version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "8443:8443"  # pgAdmin HTTPS
      - "9001:9001"  # MinIO Console HTTPS
      - "9000:9000"  # MinIO API HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - pgadmin
      - minio
      - cert-generator
    networks:
      - app-network

  cert-generator:
    image: alpine:latest
    container_name: cert-generator
    volumes:
      - ./certs:/certs
    command: >
      sh -c "
        apk add --no-cache openssl &&
        if [ ! -f /certs/public.crt ]; then
          echo 'Generating SSL certificates...' &&
          
          openssl req -x509 -newkey rsa:4096 -keyout /certs/private.key -out /certs/public.crt -days 365 -nodes -subj '/C=US/ST=State/L=City/O=Organization/CN=localhost' &&
          
          chmod 600 /certs/private.key &&
          chmod 644 /certs/public.crt &&
          
          echo 'SSL certificates generated successfully!'
        else
          echo 'SSL certificates already exist, skipping generation.'
        fi
      "

  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio-server
    restart: always
    # Removed direct port exposure - only accessible through nginx
    volumes:
      - miniodata:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    # Removed direct port exposure - only accessible through nginx
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_SERVER_MODE: "True"
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  miniodata:
  pgadmin-data:
