version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp-server
    restart: always
    environment:
      PUBLICHOST: ${PUBLICHOST}
      FTP_USER_NAME: ${FTP_USER_NAME}
      FTP_USER_PASS: ${FTP_USER_PASS}
      FTP_USER_HOME: ${FTP_USER_HOME}
    volumes:
      - ftpdata:/home/ftpusers
    ports:
      - "21:21"
      - "30000-30009:30000-30009"  # Passive mode ports

volumes:
  pgdata:
  ftpdata:
