version: '3.8'

services:
  cert-generator:
    image: alpine:latest
    container_name: cert-generator
    volumes:
      - ./certs:/certs
    command: >
      sh -c "
        apk add --no-cache openssl &&
        if [ ! -f /certs/pgladmin/server.cert ]; then
          echo 'Generating SSL certificates...' &&
          mkdir -p /certs/pgladmin &&
          
          openssl req -x509 -newkey rsa:4096 -keyout /certs/private.key -out /certs/public.crt -days 365 -nodes -subj '/C=US/ST=State/L=City/O=Organization/CN=localhost' &&
          
          openssl req -x509 -newkey rsa:4096 -keyout /certs/pgladmin/server.key -out /certs/pgladmin/server.cert -days 365 -nodes -subj '/C=US/ST=State/L=City/O=Organization/CN=localhost' &&
          
          chmod 644 /certs/private.key /certs/pgladmin/server.key &&
          chmod 644 /certs/public.crt /certs/pgladmin/server.cert &&
          chmod 755 /certs/pgladmin &&
          
          echo 'SSL certificates generated successfully!'
        else
          echo 'SSL certificates already exist, skipping generation.'
        fi
      "

  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio-server
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
      - ./certs:/root/.minio/certs
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001" --certs-dir /root/.minio/certs
    depends_on:
      cert-generator:
        condition: service_completed_successfully

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_ENABLE_TLS: "True"
      PGADMIN_SERVER_MODE: "True"
      PGADMIN_CONFIG_SERVER_MODE: "True"
    volumes:
      - pgladmin-data:/var/lib/pgladmin
      - ./certs/pgladmin:/certs
    depends_on:
      postgres:
        condition: service_started
      cert-generator:
        condition: service_completed_successfully

volumes:
  pgdata:
  miniodata:
  pgladmin-data:
