version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  sftp:
    image: atmoz/sftp
    container_name: sftp-server
    restart: always
    ports:
      - "22:22"
    volumes:
      - sftpdata:/home/${FTP_USER_NAME}
    command: "${FTP_USER_NAME}:${FTP_USER_PASS}:1001::upload"

volumes:
  pgdata:
  sftpdata:
